config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'test'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
    member do
      get 'chef'
    end
    collection do
      get 'top'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def chef
    @chef = @restaurant.chef
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :chef)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'back', restaurants_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>

app/views/pages/home.html.erb
<h1>Homepage</h1>

<% if false %>
  <%= Time.now %>
<% end %>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :rating %>
  <%= f.input :chef %>
  <%= f.submit %>
<% end %>

app/views/restaurants/chef.html.erb
<h1><%= @chef %></h1>

<p>description du chef</p>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <div>
      <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
    </div>
  <% end %>
</ul>
<%= link_to 'New Restaurant', new_restaurant_path %>
<%= link_to 'Top Restaurants', top_restaurants_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Ce restaurant a une note moyenne de <%= @restaurant.rating %></p>

<%= link_to "Voir le chef", chef_restaurant_path(@restaurant) %>
<%= link_to "Editer un restaurant", edit_restaurant_path(@restaurant) %>
<%= link_to "Supprimer #{@restaurant.name}", restaurant_path(@restaurant), method: :delete %>

<h2>Reviews</h2>
<%= link_to "Laissez un avis", new_restaurant_review_path(@restaurant) %>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.rating %> - <%= review.content %></li>
  <% end %>
</ul>

app/views/restaurants/top.html.erb
<h1>Top Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= restaurant.name %></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>